spring.application.name=auth_engine
# Change port from default 8080
server.port=8081
# Bind to specific IP (default: all interfaces)
server.address=127.0.0.1
# Connection timeout
server.tomcat.connection-timeout=20s
# Max threads (default: 200)
server.tomcat.max-threads=300
# HTTP header size limit
server.max-http-request-header-size=16KB
spring.datasource.url=${NEON_URL}
spring.datasource.username=${NEON_USER}
spring.datasource.password=${NEON_PASS}

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.security.authentication.ProviderManager=DEBUG
logging.level.org.springframework.beans=DEBUG
logging.level.org.raghul.auth_engine=DEBUG
trace=false



