spring.application.name=auth_engine
# Change port from default 8080
server.port=8081
# Bind to specific IP (default: all interfaces)
server.address=127.0.0.1
# Connection timeout
server.tomcat.connection-timeout=20s
# Max threads (default: 200)
server.tomcat.max-threads=300
# HTTP header size limit
server.max-http-request-header-size=16KB
spring.datasource.url=jdbc:postgresql://ep-weathered-bread-ahkgnp9e-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_0EWe7vaKwCno&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update




